# 通用物体放置任务配置
task_name: "place_object"
description: "将物体从一个位置移动到另一个位置"
version: "1.0"

# ============== 任务参数 ==============
parameters:
  source_object: "{source_object}"      # 源物体名称 (运行时参数)
  target_location: "{target_location}"  # 目标位置 (运行时参数)
  approach_height: 0.1                  # 接近高度 (m)
  grasp_height: 0.028                   # 抓取高度偏移 (m)
  transport_height: 0.13                # 运输高度 (m)
  place_height: 0.04                    # 放置高度偏移 (m)
  retreat_height: 0.05                  # 撤退高度 (m)

# ============== 任务状态序列 ==============
states:
  # 状态1: 接近物体上方
  - name: "approach_object"
    description: "移动到物体上方准备抓取"
    primitive: "move_to_object"
    params:
      object_name: "{source_object}"
      offset: [0, 0, "{approach_height}"]
      approach_direction: "top_down"
      orientation: "default"
    coordinate_system: "world"
    gripper_action:
      state: "open"
    timeout: 5.0
    success_criteria:
      position_tolerance: 0.01
      
  # 状态2: 下降到抓取位置
  - name: "pre_grasp"
    description: "下降到物体抓取位置"
    primitive: "move_to_object"
    params:
      object_name: "{source_object}"
      offset: [0, 0, "{grasp_height}"]
      approach_direction: "top_down"
    coordinate_system: "world"
    timeout: 3.0
    
  # 状态3: 抓取物体
  - name: "grasp"
    description: "抓取物体"
    primitive: "grasp_object"
    params:
      object_name: "{source_object}"
      grasp_type: "pinch"
      force: 0.5
    timeout: 2.0
    success_criteria:
      type: "grasp_success"
      check_method: "gripper_position"
      
  # 状态4: 提升物体
  - name: "lift"
    description: "提升被抓取的物体"
    primitive: "move_relative"
    params:
      offset: [0, 0, 0.07]
    coordinate_system: "world"
    timeout: 2.0
    
  # 状态5: 运输到目标上方
  - name: "transport"
    description: "将物体运输到目标位置上方"
    primitive: "move_to_pose"
    params:
      target_frame: "{target_location}"
      offset: [0, 0, "{transport_height}"]
    coordinate_system: "world"
    timeout: 8.0
    
  # 状态6: 下降到放置位置
  - name: "place"
    description: "下降到放置位置"
    primitive: "move_relative"
    params:
      offset: [0, 0, "-{place_height}"]
    coordinate_system: "world"
    timeout: 3.0
    
  # 状态7: 释放物体
  - name: "release"
    description: "释放物体"
    primitive: "release_object"
    params:
      release_type: "gentle"
      delay: 0.5
    timeout: 2.0
    
  # 状态8: 撤退
  - name: "retreat"
    description: "撤退到安全位置"
    primitive: "move_relative"
    params:
      offset: [0, 0, "{retreat_height}"]
    coordinate_system: "world"
    timeout: 2.0

# ============== 成功条件 ==============
success_condition:
  type: "object_at_target"
  params:
    source_object: "{source_object}"
    target_location: "{target_location}"
    position_tolerance: 0.02          # 位置容差 (m)
    check_stable: true                # 检查物体是否稳定
    stable_duration: 1.0              # 稳定持续时间 (s)

# ============== 失败条件 ==============
failure_conditions:
  - type: "object_dropped"
    params:
      object_name: "{source_object}"
      
  - type: "timeout"
    params:
      max_duration: 30.0              # 最大任务时间 (s)
      
  - type: "workspace_violation"
    params:
      check_self_collision: true
      check_environment_collision: true

# ============== 安全设置 ==============
safety:
  max_velocity: 0.5                   # 最大速度 (m/s)
  max_acceleration: 1.0               # 最大加速度 (m/s²)
  emergency_stop_on_failure: true
  collision_detection: true

# ============== 可选变体 ==============
variants:
  careful:
    description: "谨慎模式，适用于易碎物体"
    parameters:
      approach_height: 0.15
      grasp_force: 0.3
      max_velocity: 0.3
      
  fast:
    description: "快速模式，适用于坚固物体"
    parameters:
      approach_height: 0.08
      grasp_force: 0.7
      max_velocity: 0.8 