# 机械臂操作原语定义
# 参考RT-1/RT-2和Open-X Embodiment数据集

primitives:
  # ============== 基础移动原语 ==============
  move_to_pose:
    description: "移动到绝对位姿"
    params:
      - target_frame      # 目标坐标系名称
      - offset           # 相对偏移 [x, y, z] (m)
      - orientation      # 目标姿态 (可选，默认保持当前)
      - coordinate_system # 坐标系参考
    returns: bool         # 是否成功到达
    
  move_relative:
    description: "相对当前位置移动"
    params:
      - offset           # 相对偏移 [x, y, z] (m)
      - coordinate_system # 坐标系参考 (world/robot_base/end_effector)
    returns: bool
    
  move_to_object:
    description: "移动到物体位置"
    params:
      - object_name      # 物体名称
      - offset           # 相对物体的偏移 [x, y, z]
      - approach_direction # 接近方向 (top_down/front/back/left/right)
      - orientation      # 末端执行器姿态 (可选)
    returns: bool
    
  # ============== 抓取原语 ==============
  grasp_object:
    description: "抓取指定物体"
    params:
      - object_name      # 物体名称
      - grasp_type      # 抓取类型 (pinch/power/precision)
      - force           # 抓取力度 [0.0-1.0]
      - timeout         # 超时时间 (秒)
    returns: bool        # 是否成功抓取
    
  release_object:
    description: "释放当前抓取的物体"
    params:
      - release_type    # 释放类型 (gentle/quick)
      - delay           # 释放后等待时间 (秒)
    returns: bool
    
  set_gripper:
    description: "设置夹爪状态"
    params:
      - state           # open/close/position
      - position        # 具体位置 [0.0-1.0] (当state为position时)
      - force           # 力度限制
    returns: bool
    
  # ============== 操作原语 ==============
  push_object:
    description: "推动物体"
    params:
      - object_name     # 物体名称
      - direction       # 推动方向 (forward/backward/left/right) 或 [x,y,z]向量
      - distance        # 推动距离 (m)
      - force           # 推动力度 [0.0-1.0]
      - contact_offset  # 接触偏移 [x,y,z]
    returns: bool
    
  pull_object:
    description: "拉动物体"
    params:
      - object_name     # 物体名称
      - direction       # 拉动方向
      - distance        # 拉动距离 (m)
      - force           # 拉动力度
    returns: bool
    
  rotate_object:
    description: "旋转物体"
    params:
      - object_name     # 物体名称
      - axis            # 旋转轴 (x/y/z) 或 [x,y,z]向量
      - angle           # 旋转角度 (弧度)
      - speed           # 旋转速度
    returns: bool
    
  # ============== 铰接操作原语 ==============
  open_articulated:
    description: "打开铰接物体（抽屉、门等）"
    params:
      - object_name     # 物体名称
      - handle_site     # 把手位置site名称
      - open_direction  # 打开方向 [x,y,z]向量
      - distance        # 打开距离 (m)
      - speed           # 操作速度
    returns: bool
    
  close_articulated:
    description: "关闭铰接物体"
    params:
      - object_name     # 物体名称
      - handle_site     # 把手位置site名称
      - close_direction # 关闭方向 [x,y,z]向量
      - distance        # 关闭距离 (m)
    returns: bool
    
  # ============== 等待原语 ==============
  wait:
    description: "等待指定时间"
    params:
      - duration        # 等待时间 (秒)
    returns: bool
    
  wait_for_condition:
    description: "等待满足条件"
    params:
      - condition_type  # 条件类型 (object_stationary/grasp_stable/joint_at_position)
      - condition_params # 条件参数
      - timeout         # 超时时间 (秒)
    returns: bool
    
  # ============== 复合原语 ==============
  pick_and_place:
    description: "完整的拿取放置动作"
    params:
      - source_object   # 源物体
      - target_location # 目标位置
      - approach_height # 接近高度 (m)
      - grasp_type     # 抓取类型
    returns: bool
    
  stack_objects:
    description: "将一个物体堆叠到另一个上面"
    params:
      - bottom_object   # 底部物体
      - top_object      # 顶部物体
      - stack_offset    # 堆叠偏移 [x,y,z]
    returns: bool

# ============== 坐标系定义 ==============
coordinate_systems:
  world:
    description: "世界坐标系"
    reference: "MuJoCo世界坐标原点"
    
  robot_base:
    description: "机械臂基座坐标系"
    reference: "机械臂基座link的坐标系"
    
  end_effector:
    description: "末端执行器坐标系"
    reference: "末端执行器当前位置和姿态"
    
  object:
    description: "目标物体坐标系"
    reference: "物体当前位置和姿态"

# ============== 方向定义 ==============
directions:
  approach_directions:
    top_down: [0, 0, -1]      # 从上方接近
    bottom_up: [0, 0, 1]      # 从下方接近
    front: [1, 0, 0]          # 从前方接近
    back: [-1, 0, 0]          # 从后方接近
    left: [0, 1, 0]           # 从左侧接近
    right: [0, -1, 0]         # 从右侧接近
    
  push_directions:
    forward: [1, 0, 0]
    backward: [-1, 0, 0]
    left: [0, 1, 0]
    right: [0, -1, 0]
    up: [0, 0, 1]
    down: [0, 0, -1]

# ============== 抓取类型定义 ==============
grasp_types:
  pinch:
    description: "精确抓取，适用于小物体"
    force_range: [0.1, 0.5]
    
  power:
    description: "力量抓取，适用于大物体"
    force_range: [0.3, 1.0]
    
  precision:
    description: "精密抓取，适用于易碎物体"
    force_range: [0.05, 0.3] 