# AirBot Play机械臂配置
robot_name: "airbot_play"
description: "AirBot Play 6-DOF桌面协作机械臂"

# ============== 机械臂结构配置 ==============
kinematics:
  base_link: "arm_base"              # 基座连杆名称
  end_effector_site: "endpoint"      # 末端执行器site名称
  qpos_dim: 8                        # qpos维度 (6臂+2夹爪)
  ctrl_dim: 7                        # ctrl维度 (6臂+1夹爪)
  arm_joints: 6                      # 机械臂关节数
  arm_joint_names:                   # 机械臂关节名称 (按顺序)
    - "joint1"
    - "joint2"
    - "joint3"
    - "joint4"
    - "joint5"
    - "joint6"
    
# ============== 夹爪配置 ==============
gripper:
  type: "two_finger_tendon"          # 夹爪类型 (tendon控制双指)
  ctrl_dim: 1                        # 控制器维度
  ctrl_index: 6                      # 夹爪控制器索引 (0-based)
  qpos_joints: ["endleft", "endright"]  # qpos关节名称
  qpos_indices: [6, 7]               # qpos关节索引 (0-based)
  tendon_name: "gripper_gear"        # tendon名称
  ctrl_range: [0.0, 1.0]            # 控制范围 (0=闭合, 1=打开)
  default_position: 1.0              # 默认位置 (完全打开)
  close_position: 0.0                # 关闭位置
  grasp_threshold: 0.5               # 抓取检测阈值
  sensor_name: "gripper_pos"         # 传感器名称

# ============== 控制配置 ==============
control:
  control_mode: "position"           # 控制模式 (position/velocity/effort)
  update_rate: 500                   # 控制频率 (Hz)
  smoothing: true                    # 启用轨迹平滑
  interpolation_type: "linear"       # 插值类型
  
  # 执行器配置 (按MuJoCo控制器顺序)
  actuators:
    - name: "joint1"                 # 机械臂关节1
      type: "position"
    - name: "joint2"                 # 机械臂关节2  
      type: "position"
    - name: "joint3"                 # 机械臂关节3
      type: "position"
    - name: "joint4"                 # 机械臂关节4
      type: "position"
    - name: "joint5"                 # 机械臂关节5
      type: "position"
    - name: "joint6"                 # 机械臂关节6
      type: "position"
    - name: "gripper"                # 夹爪tendon控制
      type: "tendon"

# ============== 坐标系配置 ==============
coordinate_frames:
  base_frame: "arm_base"             # 基座坐标系
  planning_frame: "arm_base"         # 规划坐标系
  tcp_frame: "endpoint"              # 工具中心点坐标系

# ============== 传感器配置 ==============
sensors:
  # 关节位置传感器 (按顺序)
  joint_pos_sensors:
    - "joint1_pos"
    - "joint2_pos"
    - "joint3_pos"
    - "joint4_pos"
    - "joint5_pos"
    - "joint6_pos"
    - "gripper_pos"  # 夹爪肌腱位置
  
  # 关节速度传感器 (按顺序)
  joint_vel_sensors:
    - "joint1_vel"
    - "joint2_vel"
    - "joint3_vel"
    - "joint4_vel"
    - "joint5_vel"
    - "joint6_vel"
    - "gripper_vel"  # 夹爪肌腱速度
  
  # 关节力矩传感器 (按顺序)
  joint_torque_sensors:
    - "joint1_torque"
    - "joint2_torque"
    - "joint3_torque"
    - "joint4_torque"
    - "joint5_torque"
    - "joint6_torque"
    - "gripper_torque"  # 夹爪力矩
  
  # 末端执行器传感器
  end_effector_sensors:
    position: "endpoint_pos"         # 末端位置
    orientation: "endpoint_quat"     # 末端姿态
    velocity: "endpoint_vel"         # 末端速度
    gyro: "endpoint_gyro"            # 末端角速度
    accelerometer: "endpoint_acc"    # 末端加速度

# ============== 特殊配置 ==============
special_features:
  compliance_control: false          # 柔顺控制能力
  cartesian_impedance: false         # 笛卡尔阻抗控制
  nullspace_control: true            # 零空间控制

# ============== IK求解配置 ==============
ik_solver:
  solver_type: "quadprog"            # 使用quadprog求解器
  position_tolerance: 0.035          # 位置收敛阈值 (m) - 3.5cm (放宽至达标精度)
  orientation_tolerance: 0.5         # 姿态收敛阈值 (rad) - 放宽
  max_iterations: 50                 # 增加最大迭代次数
  damping: 1.0                       # LM阻尼系数
  position_cost: 100.0               # 位置任务权重
  orientation_cost: 10.0             # 姿态权重
  posture_cost: 0.01                 # 姿态保持权重
  dt: 0.002                          # 积分时间步长

# ============== MJCF模型路径 ==============
mjcf_model:
  base_path: "models/mjcf/manipulator/airbot_play/airbot_play.xml"
  dependencies:
    - "models/mjcf/manipulator/airbot_play/airbot_play_dependencies.xml"
    - "models/mjcf/manipulator/airbot_play/airbot_play_control.xml"
    - "models/mjcf/manipulator/airbot_play/airbot_play_sensor.xml"
    - "models/mjcf/manipulator/airbot_play/airbot_play_appendix.xml" 