# KUKA IIWA14机械臂配置
robot_name: "iiwa14"
description: "KUKA LBR iiwa 14 R820 7-DOF协作机械臂"

# ============== 机械臂结构配置 ==============
kinematics:
  base_link: "base"                  # 基座连杆名称
  end_effector_site: "endpoint"      # 末端执行器site名称
  qpos_dim: 9                        # qpos维度 (7臂+2夹爪)
  ctrl_dim: 8                        # ctrl维度 (7臂+1夹爪)
  arm_joints: 7                      # 机械臂关节数
  arm_joint_names:                   # 机械臂关节名称 (按顺序)
    - "joint1"
    - "joint2"
    - "joint3"
    - "joint4"
    - "joint5"
    - "joint6"
    - "joint7"
    
# ============== 夹爪配置 ==============
gripper:
  type: "two_finger_tendon"          # 夹爪类型 (tendon控制双指)
  ctrl_dim: 1                        # 控制器维度
  ctrl_index: 7                      # 夹爪控制器索引 (0-based)
  qpos_joints: ["right_driver_joint", "left_driver_joint"]  # qpos关节名称
  qpos_indices: [7, 8]               # qpos关节索引 (0-based)
  tendon_name: "split"               # 腱名称
  ctrl_range: [0.0, 0.8]             # 控制范围 (0=打开, 0.8=关闭)
  default_position: 0.0              # 默认位置 (完全打开)
  close_position: 0.8                # 关闭位置
  grasp_threshold: 0.4               # 抓取检测阈值

# ============== 控制配置 ==============
control:
  control_mode: "position"           # 控制模式 (position/velocity/effort)
  update_rate: 500                   # 控制频率 (Hz)
  smoothing: true                    # 启用轨迹平滑
  interpolation_type: "cubic"        # 插值类型
  
  # 执行器配置 (按MuJoCo控制器顺序)
  actuators:
    - name: "actuator1"              # 机械臂关节1
      type: "general"
    - name: "actuator2"              # 机械臂关节2  
      type: "general"
    - name: "actuator3"              # 机械臂关节3
      type: "general"
    - name: "actuator4"              # 机械臂关节4
      type: "general"
    - name: "actuator5"              # 机械臂关节5
      type: "general"
    - name: "actuator6"              # 机械臂关节6
      type: "general"
    - name: "actuator7"              # 机械臂关节7
      type: "general"
    - name: "fingers_actuator"       # 夹爪控制
      type: "tendon"

# ============== 工作空间配置 ==============
workspace:
  position_limits:
    x: [-0.85, 0.85]                 # X轴范围 (m)
    y: [-0.85, 0.85]                 # Y轴范围 (m)  
    z: [0.1, 1.4]                    # Z轴范围 (m)
  velocity_limits: [1.7, 1.7, 1.7]  # 线速度限制 (m/s)
  acceleration_limits: [3.5, 3.5, 3.5]  # 线加速度限制 (m/s²)

# ============== IK求解配置 ==============
ik_solver:
  solver_type: "quadprog"            # 使用quadprog求解器
  position_tolerance: 0.01           # 位置收敛阈值 (m) 
  orientation_tolerance: 0.05        # 姿态收敛阈值 (rad)
  max_iterations: 50                 # 最大迭代次数
  damping: 1.0                       # LM阻尼系数
  position_cost: 100.0               # 位置任务权重
  orientation_cost: 10.0             # 姿态权重
  posture_cost: 0.01                 # 姿态保持权重
  dt: 0.002                          # 积分时间步长

# ============== 坐标系配置 ==============
coordinate_frames:
  base_frame: "base"                 # 基座坐标系
  planning_frame: "base"             # 规划坐标系
  tcp_frame: "endpoint"              # 工具中心点坐标系

# ============== 传感器配置 ==============
sensors:
  joint_states: true                 # 关节状态传感器
  end_effector_wrench: false         # 末端力/力矩传感器
  joint_torques: true                # 关节力矩传感器

# ============== 安全配置 ==============
safety:
  joint_limits_check: true          # 启用关节限制检查
  workspace_check: true             # 启用工作空间检查
  collision_check: false            # 碰撞检测 (暂未实现)
  emergency_stop: true              # 紧急停止功能

# ============== 特殊配置 ==============
special_features:
  compliance_control: true           # 柔顺控制能力
  cartesian_impedance: true          # 笛卡尔阻抗控制
  nullspace_control: true            # 零空间控制
  precise_positioning: true          # 精密定位能力
  
# ============== MJCF模型路径 ==============
mjcf_model:
  base_path: "models/mjcf/manipulator/robot_iiwa14.xml"
  dependencies:
    - "models/mjcf/manipulator/kuka_iiwa_14/"
