# Franka Emika Panda机械臂配置
robot_name: "panda"
description: "Franka Emika Panda 7-DOF协作机械臂"

# ============== 机械臂结构配置 ==============
kinematics:
  base_link: "panda_link0"           # 基座连杆名称
  end_effector_site: "endpoint"      # 末端执行器site名称
  qpos_dim: 9                        # qpos维度 (7臂+2夹爪)
  ctrl_dim: 8                        # ctrl维度 (7臂+1夹爪)
  arm_joints: 7                      # 机械臂关节数
  posture_cost: 0.01                 # 姿态保持权重
  dt: 0.002                          # 积分时间步长 (参考示例)ika Panda 7-DOF协作机械臂"

# ============== 机械臂结构配置 ==============
kinematics:
  base_link: "panda_link0"           # 基座连杆名称
  end_effector_site: "endpoint"      # 末端执行器site名称
  qpos_dim: 9                        # qpos维度 (7臂+2夹爪)
  ctrl_dim: 8                        # ctrl维度 (7臂+1夹爪)
  arm_joints: 7                      # 机械臂关节数
  arm_joint_names:                   # 机械臂关节名称 (按顺序)
    - "joint1"
    - "joint2" 
    - "joint3"
    - "joint4"
    - "joint5"
    - "joint6"
    - "joint7"
    
# ============== 夹爪配置 ==============
gripper:
  type: "two_finger_equality"        # 夹爪类型 (equality约束双指)
  ctrl_dim: 1                        # 控制器维度
  ctrl_index: 7                      # 夹爪控制器索引 (0-based)
  qpos_joints: ["finger_joint1", "finger_joint2"]  # qpos关节名称
  qpos_indices: [7, 8]               # qpos关节索引 (0-based)
  ctrl_range: [0.0, 0.04]            # 控制范围 (m, 0=闭合, 0.04=打开)
  default_position: 0.04             # 默认位置 (完全打开)
  close_position: 0.00               # 关闭位置
  grasp_threshold: 0.02              # 抓取检测阈值

# ============== 控制配置 ==============
control:
  control_mode: "position"           # 控制模式 (position/velocity/effort)
  update_rate: 500                   # 控制频率 (Hz)
  smoothing: true                    # 启用轨迹平滑
  interpolation_type: "cubic"        # 插值类型
  
  # 执行器配置 (按MuJoCo控制器顺序)
  actuators:
    - name: "actuator1"              # 机械臂关节1
      type: "position"
    - name: "actuator2"              # 机械臂关节2  
      type: "position"
    - name: "actuator3"              # 机械臂关节3
      type: "position"
    - name: "actuator4"              # 机械臂关节4
      type: "position"
    - name: "actuator5"              # 机械臂关节5
      type: "position"
    - name: "actuator6"              # 机械臂关节6
      type: "position"
    - name: "actuator7"              # 机械臂关节7
      type: "position"
    - name: "actuator8"              # 夹爪控制
      type: "general"

# ============== IK求解配置 ==============
ik_solver:
  solver_type: "quadprog"            # 使用quadprog求解器
  position_tolerance: 0.002          # 位置收敛阈值 (m) 
  orientation_tolerance: 0.02        # 姿态收敛阈值 (rad)
  max_iterations: 50                 # 增加最大迭代次数
  damping: 1.0                       # LM阻尼系数
  position_cost: 100.0               # 位置任务权重
  orientation_cost: 10.0             # 姿态权重
  posture_cost: 0.01                 # 姿态保持权重
  dt: 0.002                          # 积分时间步长

# ============== 坐标系配置 ==============
coordinate_frames:
  base_frame: "panda_link0"          # 基座坐标系
  planning_frame: "panda_link0"      # 规划坐标系
  tcp_frame: "attachment_site"       # 工具中心点坐标系

# ============== 传感器配置 ==============
sensors:
  joint_states: true                 # 关节状态传感器
  end_effector_wrench: false         # 末端力/力矩传感器
  joint_torques: true                # 关节力矩传感器

# ============== MJCF模型路径 ==============
mjcf_model:
  base_path: "models/mjcf/manipulator/robot_panda.xml"
  dependencies:
    - "models/mjcf/manipulator/franka_emika_panda/" 