# 睿尔曼RM65机械臂配置
robot_name: "rm65"
description: "睿尔曼RM65 6-DOF协作机械臂 - 多指夹爪"

# ============== 机械臂结构配置 ==============
kinematics:
  base_link: "base_link"             # 基座连杆名称
  end_effector_site: "endpoint"      # 末端执行器site名称
  qpos_dim: 12                       # qpos维度 (6臂+6夹爪)
  ctrl_dim: 7                        # ctrl维度 (6臂+1夹爪主控制)
  arm_joints: 6                      # 机械臂关节数
  arm_joint_names:                   # 机械臂关节名称 (按顺序)
    - "joint1"
    - "joint2" 
    - "joint3"
    - "joint4"
    - "joint5"
    - "joint6"
    
# ============== 夹爪配置 ==============
gripper:
  type: "multi_finger_equality"       # 夹爪类型 (多指夹爪，equality约束)
  ctrl_dim: 1                        # 控制器维度
  ctrl_index: 6                      # 夹爪控制器索引 (0-based)
  qpos_joints: ["gripper_joint1", "gripper_joint2", "gripper_joint3", "gripper_joint4", "gripper_joint5", "gripper_joint6"]  # qpos关节名称
  qpos_indices: [6, 7, 8, 9, 10, 11] # qpos关节索引 (0-based)
  ctrl_range: [0.0, 0.82]           # 控制范围 (0=闭合, 0.82=打开)
  default_position: 0.82             # 默认位置 (打开)
  close_position: 0.0                # 关闭位置  
  open_position: 0.82                # 打开位置
  grasp_threshold: 0.4               # 抓取检测阈值

# ============== 控制配置 ==============
control:
  control_mode: "position"           # 控制模式 (position/velocity/effort)
  update_rate: 500                   # 控制频率 (Hz)
  smoothing: true                    # 启用轨迹平滑
  interpolation_type: "cubic"        # 插值类型
  
  # 执行器配置 (按MuJoCo控制器顺序)
  actuators:
    - name: "joint1"                 # 机械臂关节1
      type: "position"
      ctrlrange: [-3.1, 3.1]
    - name: "joint2"                 # 机械臂关节2  
      type: "position"
      ctrlrange: [-2.268, 2.268]
    - name: "joint3"                 # 机械臂关节3
      type: "position"
      ctrlrange: [-2.355, 2.355]
    - name: "joint4"                 # 机械臂关节4
      type: "position"
      ctrlrange: [-3.1, 3.1]
    - name: "joint5"                 # 机械臂关节5
      type: "position"
      ctrlrange: [-2.233, 2.233]
    - name: "joint6"                 # 机械臂关节6
      type: "position"
      ctrlrange: [-6.28, 6.28]
    - name: "gripper"                # 夹爪主控制
      type: "position"
      ctrlrange: [0.0, 0.82]

# ============== IK求解配置 ==============
ik_solver:
  solver_type: "quadprog"            # 使用quadprog求解器
  position_tolerance: 0.01           # 位置收敛阈值 (m) 
  orientation_tolerance: 0.05        # 姿态收敛阈值 (rad)
  max_iterations: 50                 # 最大迭代次数
  damping: 1.0                       # LM阻尼系数
  position_cost: 100.0               # 位置任务权重
  orientation_cost: 10.0             # 姿态权重
  posture_cost: 0.01                 # 姿态保持权重
  dt: 0.002                          # 积分时间步长

# ============== 坐标系配置 ==============
coordinate_frames:
  base_frame: "base_link"            # 基座坐标系
  planning_frame: "base_link"        # 规划坐标系
  tcp_frame: "endpoint"              # 工具中心点坐标系

# ============== 传感器配置 ==============
sensors:
  joint_states: true                 # 关节状态传感器
  end_effector_wrench: false         # 末端力/力矩传感器
  joint_torques: true                # 关节力矩传感器
  camera: true                       # 集成相机

# ============== MJCF模型路径 ==============
mjcf_model:
  base_path: "models/mjcf/manipulator/robot_rm65.xml"
  dependencies:
    - "models/mjcf/manipulator/realman_rm65/" 
