# Universal Robots UR5e机械臂配置
robot_name: "ur5e"
description: "Universal Robots UR5e 6-DOF工业机械臂"

# ============== 机械臂结构配置 ==============
kinematics:
  base_link: "base"                  # 基座连杆名称
  end_effector_site: "endpoint"      # 末端执行器site名称
  qpos_dim: 8                        # qpos维度 (6臂+2夹爪)
  ctrl_dim: 7                        # ctrl维度 (6臂+1夹爪)
  arm_joints: 6                      # 机械臂关节数
  arm_joint_names:                   # 机械臂关节名称 (按顺序)
    - "shoulder_pan_joint"
    - "shoulder_lift_joint"
    - "elbow_joint"
    - "wrist_1_joint"
    - "wrist_2_joint"
    - "wrist_3_joint"
    
# ============== 夹爪配置 ==============
gripper:
  type: "two_finger_single"          # 夹爪类型 (单关节控制+被动跟随)
  ctrl_dim: 1                        # 控制器维度
  ctrl_index: 6                      # 夹爪控制器索引 (0-based)
  qpos_joints: ["base_joint_gripper_left", "base_joint_gripper_right"]  # qpos关节名称
  qpos_indices: [6, 7]               # qpos关节索引 (0-based)
  primary_joint: "base_joint_gripper_right"  # 主控制关节
  ctrl_range: [0.0, 0.055]          # 控制范围 (m, 0=闭合, 0.055=打开)
  default_position: 0.055            # 默认位置 (完全打开)
  close_position: 0.0                # 关闭位置
  grasp_threshold: 0.025             # 抓取检测阈值

# ============== 控制配置 ==============
control:
  control_mode: "position"           # 控制模式 (position/velocity/effort)
  update_rate: 500                   # 控制频率 (Hz)
  smoothing: true                    # 启用轨迹平滑
  interpolation_type: "linear"       # 插值类型
  
  # 执行器配置 (按MuJoCo控制器顺序)
  actuators:
    - name: "shoulder_pan"           # 机械臂关节1
      type: "position"
    - name: "shoulder_lift"          # 机械臂关节2  
      type: "position"
    - name: "elbow"                  # 机械臂关节3
      type: "position"
    - name: "wrist_1"                # 机械臂关节4
      type: "position"
    - name: "wrist_2"                # 机械臂关节5
      type: "position"
    - name: "wrist_3"                # 机械臂关节6
      type: "position"
    - name: "gripper"                # 夹爪控制
      type: "position"

# ============== 传感器配置 ==============
sensors:
  joint_pos_sensors:
    - "shoulder_pan_pos"
    - "shoulder_lift_pos"
    - "elbow_pos"
    - "wrist_1_pos"
    - "wrist_2_pos"
    - "wrist_3_pos"
    - "gripper_pos"

  end_effector_sensors:
    position: "endpoint_pos"         # 末端位置
    orientation: "endpoint_quat"     # 末端姿态

# ============== IK求解配置 ==============
ik_solver:
  solver_type: "quadprog"            # 使用quadprog求解器
  position_tolerance: 0.002          # 位置收敛阈值 (m) 
  orientation_tolerance: 0.02        # 姿态收敛阈值 (rad)
  max_iterations: 50                 # 增加最大迭代次数
  damping: 1.0                       # LM阻尼系数
  position_cost: 100.0               # 位置任务权重
  orientation_cost: 10.0             # 姿态权重
  posture_cost: 0.01                 # 姿态保持权重
  dt: 0.002                          # 积分时间步长
