# Universal Robots UR5e机械臂配置
robot_name: "ur5e"
description: "Universal Robots UR5e 6-DOF工业机械臂"

# ============== 机械臂结构配置 ==============
kinematics:
  base_link: "base"                  # 基座连杆名称
  end_effector_site: "endpoint"      # 末端执行器site名称
  qpos_dim: 8                        # qpos维度 (6臂+2夹爪)
  ctrl_dim: 7                        # ctrl维度 (6臂+1夹爪)
  arm_joints: 6                      # 机械臂关节数
  arm_joint_names:                   # 机械臂关节名称 (按顺序)
    - "shoulder_pan_joint"
    - "shoulder_lift_joint"
    - "elbow_joint"
    - "wrist_1_joint"
    - "wrist_2_joint"
    - "wrist_3_joint"
    
# ============== 夹爪配置 ==============
gripper:
  type: "two_finger_single"          # 夹爪类型 (单关节控制+被动跟随)
  ctrl_dim: 1                        # 控制器维度
  ctrl_index: 6                      # 夹爪控制器索引 (0-based)
  qpos_joints: ["base_joint_gripper_left", "base_joint_gripper_right"]  # qpos关节名称
  qpos_indices: [6, 7]               # qpos关节索引 (0-based)
  primary_joint: "base_joint_gripper_right"  # 主控制关节
  ctrl_range: [0.0, 0.055]          # 控制范围 (m, 0=闭合, 0.055=打开)
  default_position: 0.055            # 默认位置 (完全打开)
  close_position: 0.0                # 关闭位置
  grasp_threshold: 0.025             # 抓取检测阈值

# ============== 控制配置 ==============
control:
  control_mode: "position"           # 控制模式 (position/velocity/effort)
  update_rate: 500                   # 控制频率 (Hz)
  smoothing: true                    # 启用轨迹平滑
  interpolation_type: "linear"       # 插值类型
  
  # 执行器配置 (按MuJoCo控制器顺序)
  actuators:
    - name: "shoulder_pan"           # 机械臂关节1
      type: "position"
    - name: "shoulder_lift"          # 机械臂关节2  
      type: "position"
    - name: "elbow"                  # 机械臂关节3
      type: "position"
    - name: "wrist_1"                # 机械臂关节4
      type: "position"
    - name: "wrist_2"                # 机械臂关节5
      type: "position"
    - name: "wrist_3"                # 机械臂关节6
      type: "position"
    - name: "gripper"                # 夹爪控制
      type: "position"

# ============== 坐标系配置 ==============
coordinate_frames:
  base_frame: "base"                 # 基座坐标系
  planning_frame: "base"             # 规划坐标系
  tcp_frame: "endpoint"              # 工具中心点坐标系

# ============== 工作空间配置 ==============
workspace:
  position_limits:
    x: [-0.8, 0.8]                   # X轴范围 (m)
    y: [-0.8, 0.8]                   # Y轴范围 (m)  
    z: [0.1, 1.2]                    # Z轴范围 (m)
  velocity_limits: [2.0, 2.0, 2.0]  # 线速度限制 (m/s)
  acceleration_limits: [5.0, 5.0, 5.0]  # 线加速度限制 (m/s²)

# ============== IK求解配置 ==============
ik_solver:
  solver_type: "quadprog"            # 使用quadprog求解器
  position_tolerance: 0.01           # 位置收敛阈值 (m) 
  orientation_tolerance: 0.05        # 姿态收敛阈值 (rad)
  max_iterations: 50                 # 增加最大迭代次数
  damping: 1.0                       # LM阻尼系数
  position_cost: 100.0               # 位置任务权重
  orientation_cost: 10.0             # 姿态权重
  posture_cost: 0.01                 # 姿态保持权重
  dt: 0.002                          # 积分时间步长

# ============== 传感器配置 ==============
sensors:
  joint_states: true                 # 关节状态传感器
  end_effector_wrench: false         # 末端力/力矩传感器
  joint_torques: true                # 关节力矩传感器

# ============== 安全配置 ==============
safety:
  joint_limits_check: true          # 启用关节限制检查
  workspace_check: true             # 启用工作空间检查
  collision_check: false            # 碰撞检测 (暂未实现)
  emergency_stop: true              # 紧急停止功能

# ============== 特殊配置 ==============
special_features:
  compliance_control: false          # 柔顺控制能力
  cartesian_impedance: false         # 笛卡尔阻抗控制
  nullspace_control: true            # 零空间控制
  industrial_grade: true             # 工业级机械臂
  
# ============== MJCF模型路径 ==============
mjcf_model:
  base_path: "models/mjcf/manipulator/robot_ur5e.xml"
  dependencies:
    - "models/mjcf/manipulator/universal_robots_ur5e/"
